<?xml version="1.0"?>
<!--
Copyright 2026 amr-sim-lab contributors
Licensed under the Apache License, Version 2.0. See LICENSE.
-->
<package format="3">
  <name>scene_spawner_interfaces</name>
  <version>0.1.0</version>
  <description>Service definitions for scene_spawner.</description>
  <maintainer email="you@example.com">amr-sim-lab contributors</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>rosidl_default_generators</buildtool_depend>

  <exec_depend>rosidl_default_runtime</exec_depend>

  <member_of_group>rosidl_interface_packages</member_of_group>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
